---
- name: Install Matomo
  hosts: all
  vars:
    mdb_dbname: "matomodb"
    mdb_username: "mariadb_admin"
    mdb_password: "pw_set_by_ansible"
    matomo_url: "http://10.0.0.72/matomo/
  become: yes
  tasks:
    - name: Start MariaDB
      action: service name=mysql state=started
    - name: Create Maria DB Database
      community.mysql.mysql_db:
        name: matomodb
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Add Admin User to MariaDB Database
      community.mysql.mysql_user:
        name: "{{ mdb_username }}"
        password: "{{ mdb_password }}"
        host: localhost
        state: present
        update_password: on_create
        priv: "{{ mdb_dbname }}.*:ALL"
    - name: Download and Extract Matomo
      ansible.builtin.unarchive:
        src: https://builds.matomo.org/matomo.zip
        dest: /var/www/html
        remote_src: yes
        creates: /var/www/html/matomo
    - name: Set Matomo Directory Permissions
        path: /var/www/html/matomo
        recurse: yes
        owner: www-data
        group: www-data
    - name: Install Matomo using HTTP requests
        block:
        - name: HTTP GET Welcome
          uri:
            url: "{{ matomo_url }}index.php?action=welcome"
            method: GET
            status_code: 200
          register: matomo_welcome
        - name: Debug Welcome HTTP GET
          debug:
            var: matomo_welcome
            verbosity: 2
        - name: Set a variable for the MATOMO_SESSID cookie
          set_fact:
            matomo_session_cookie: "MATOMO_SESSID={{ cookie.value }}"
          when: cookie.key == "MATOMO_SESSID"
          loop: "{{ matomo_welcome.cookies | dict2items }}"
          loop_control:
            loop_var: cookie
        - name: Pause
          pause:
            seconds: 1

